KingFoo\BookmarkerBundle\Entity\Bookmark:
    properties:
        user:
            - NotBlank: ~
        url:
            - NotBlank: ~
            - Url: ~
        description:
            - NotBlank: ~
            - Length: { min: 5, max: 500 }
        tags:
            - NotBlank: ~
            - Count: { min: 1, max: 10 }

KingFoo\BookmarkerBundle\Entity\Tag:
    properties:
        label:
            - NotBlank: ~
            - Length: { max: 50 }

KingFoo\BookmarkerBundle\Entity\User:
    properties:
        username:
            - NotBlank: ~
            - Length: { max: 50 }
        email:
            - NotBlank: ~
            - Email: ~
        roles:
            - NotBlank: ~
            - Count: { min: 1 }
